channels:
  - defaults
dependencies:
  - autopep8=1.5.7
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - conda=4.10.3
  - conda-package-handling=1.7.3
  - cryptography=35.0.0
  - flake8=3.9.2
  - freetype=2.11.0
  - giflib=5.2.1
  - icu=58.2
  - idna=3.2
  - importlib-metadata=4.8.1
  - lcms2=2.12
  - libffi=3.3
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libxslt=1.1.34
  - lxml=4.6.3
  - lz4-c=1.9.3
  - mccabe=0.6.1
  - ncurses=6.2
  - olefile=0.46
  - openssl=1.1.1l
  - pillow=8.4.0
  - pip=21.2.4
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pyflakes=2.3.1
  - pymongo=3.12.0
  - pyopenssl=21.0.0
  - pysocks=1.7.1
  - python=3.8.12
  - readline=8.1
  - requests=2.26.0
  - ruamel_yaml=0.15.100
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - toml=0.10.2
  - tqdm=4.62.3
  - urllib3=1.26.7
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - libiconv==1.16
    - libcxx==12.0.0
